[package]
name = "houseflow-device"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-types = { path = "../../types" }
lighthouse-proto = { path = "../../lighthouse/proto" }

tokio = { version = "1.5", features = [ "rt-multi-thread", "macros", "fs" ] }
tokio-tungstenite = "0.14"
tungstenite = "0.13"
hyper = { version = "0.14", features = [ "client", "http1" ] }
hyper-tls = "0.5"
http = "0.2.4"

loggerv = "0.7"
log = "0.4"

structopt = "0.3"
anyhow = "1.0"
url = "2.2"
futures-util = "0.3.14"

