[package]
name = "houseflow-device"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-types = { path = "../../types" }
lighthouse-proto = { path = "../../lighthouse/proto" }
tokio-tungstenite = "0.14"

tokio = { version = "1.5", features = [ "rt-multi-thread", "macros" ] }
