[workspace]
members = [
  "fulfillment/api",
  "fulfillment/server",
  "auth/types",
  "auth/server",
  "db",
  "tui",
  "devices/virtual",
  "token",
  "types",
  "lighthouse/proto",
  "lighthouse/broker",
  "lighthouse/api",
  "lighthouse/types",
  "lighthouse/macros"
]
