[workspace]
members = [
  "fulfillment/types",

  "lighthouse/proto",
  "lighthouse/types",
  "lighthouse/macros",

  "auth/types",

  "config",

  "devices/virtual",

  "token",

  "server",

  "types",

  "db",

  "core",
  "api",
]
default-members = [ "core" ]
