[workspace]
members = [
  "fulfillment",
  "db",
# "tui",
  "devices/virtual",
  "token",
  "types",
  "lighthouse/proto",
  "lighthouse/broker",
  "lighthouse/api",
  "lighthouse/types",
  "lighthouse/macros"
]
