[workspace]
members = [
  "fulfillment/api",
  "fulfillment/server",
  "fulfillment/types",

  "lighthouse/proto",
  "lighthouse/server",
  "lighthouse/api",
  "lighthouse/types",
  "lighthouse/macros",

  "auth/types",
  "auth/server",
  "auth/api",

  "devices/virtual",

  "token",

  "types",

  "db",

  "core",
]
