[workspace]
members = [
  "fulfillment/api",
  "fulfillment/server",
  "fulfillment/types",
  "auth/types",
  "auth/server",
  "auth/api",
  "db",

  "devices/virtual",
  "token",
  "types",
  "lighthouse/proto",
  "lighthouse/broker",
  "lighthouse/api",
  "lighthouse/types",
  "lighthouse/macros"
  "core",
]
