version: "3.9"
services:
  nginx:
    tty: true
    build:
      context: ./build/nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443
    restart: "unless-stopped"
    volumes:
      - ./deployment/certs/fullchain.pem:/etc/dockercerts/fullchain.pem
      - ./deployment/certs/privkey.pem:/etc/dockercerts/privkey.pem

  postgres:
    image: postgres
    restart: "unless-stopped"
    env_file:
      - .env
    ports:
      - 5432:5432

  broker:
    tty: true
    restart: "unless-stopped"
    depends_on:
      - postgres
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: ./cmd/broker
    ports:
      - 1883:1883 # MQTT
      - 8083:8083 # MQTT/WS

  auth:
    tty: true
    restart: "unless-stopped"
    depends_on:
      - postgres
    build:
      dockerfile: ./cmd/auth/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./web/templates:/templates

  fulfillment:
    tty: true
    restart: "unless-stopped"
    # depends_on:
    #   - postgres
    build:
      dockerfile: ./fulfillment/Dockerfile
      context: .
    volumes:
      - ./fulfillment/src:/app/src
      - ./db:/db
    env_file:
      - .env
