version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - backend

  server-api:
    tty: true
    container_name: 'server-api'
    depends_on:
      - redis
    env_file:
      - .env
    build:
      context: $PWD/server-api
      dockerfile: Dockerfile
    ports:
      - $PORT_API:$PORT_API
    restart: 'unless-stopped'
    volumes:
      - $PWD/server-api/src/firebaseConfig.json:/app/src/firebaseConfig.json
    networks:
      - backend

  server-device:
    tty: true
    container_name: 'server-device'
    depends_on:
      - redis
      - server-api
    env_file:
      - .env
    build:
      context: $PWD/server-device
      dockerfile: Dockerfile
    ports:
      - $PORT_DEVICE:$PORT_DEVICE
    restart: 'unless-stopped'
    volumes:
      - $PWD/server-device/src/firebaseConfig.json:/app/src/firebaseConfig.json
    networks:
      - backend

  server-client:
    tty: true
    container_name: 'server-client'
    depends_on:
      - redis
      - server-device
    env_file:
      - .env
    build:
      context: $PWD/server-client
      dockerfile: Dockerfile
    ports:
      - $PORT_CLIENT:$PORT_CLIENT
    restart: 'unless-stopped'
    volumes:
      - $PWD/server-client/src/firebaseConfig.json:/app/src/firebaseConfig.json
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
