version: '3.8'
services:
  mosquitto:
    image: 'iegomez/mosquitto-go-auth'
    container_name: 'mosquitto'
    ports:
      - 1883:1883
    networks:
      - backend
    volumes:
      - ./mosquitto:/etc/mosquitto

  server-api:
    tty: true
    container_name: 'server-api'
    command: npm run start:dev
    env_file:
      - .env
    build:
      context: ./server-api
      dockerfile: Dockerfile
    ports:
      - $PORT_API:$PORT_API
    restart: 'unless-stopped'
    volumes:
      - ./firebaseConfig.json:/server/firebaseConfig.json
      - ./server-api/src:/server/src
      - ./server-api/bin:/server/bin
    networks:
      - backend

networks:
  backend:
