version: '3.8'
services:
  emqx:
    image: 'emqx/emqx'
    container_name: 'emqx'
    environment:
      - EMQX_NAME=emqx
      # - EMQX_LOG__LEVEL=debug
      - EMQX_ALLOW_ANONYMOUS=false

      - EMQX_LOADED_PLUGINS=emqx_auth_http,emqx_management,emqx_recon,emqx_retainer,emqx_dashboard
    ports:
      - 1883:1883 # MQTT
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083
    volumes:
      - ./emqx/plugins:/opt/emqx/etc/plugins

    networks:
      - backend
  server-api:
    tty: true
    container_name: 'server-api'
    command: npm run start:dev
    env_file:
      - .env
    build:
      context: ./server-api
      dockerfile: Dockerfile
    ports:
      - $PORT_API:$PORT_API
    restart: 'unless-stopped'
    volumes:
      - ./firebaseConfig.json:/server/firebaseConfig.json
      - ./server-api/src:/server/src
      - ./server-api/bin:/server/bin
    networks:
      - backend

networks:
  backend:
