version: '3.8'
services:
  server-api:
    tty: true
    container_name: 'server-api'
    env_file:
      - .env
    build:
      context: ./server-api
      dockerfile: Dockerfile
    ports:
      - $PORT_API:$PORT_API
    restart: 'unless-stopped'
    volumes:
      - ./server-api/src/firebaseConfig.json:/app/src/firebaseConfig.json
  server-client:
    tty: true
    container_name: 'server-client'
    env_file:
      - .env
    build:
      context: ./server-client
      dockerfile: Dockerfile
    ports:
      - $PORT_CLIENT:$PORT_CLIENT
    restart: 'unless-stopped'
    volumes:
      - ./server-client/src/firebaseConfig.json:/app/src/firebaseConfig.json
  server-client:
    tty: true
    container_name: 'server-device'
    env_file:
      - .env
    build:
      context: ./server-device
      dockerfile: Dockerfile
    ports:
      - $PORT_DEVICE:$PORT_DEVICE
    restart: 'unless-stopped'
    volumes:
      - ./server-device/src/firebaseConfig.json:/app/src/firebaseConfig.json