version: '3.8'
services:
  server-api:
    tty: true
    container_name: 'server-api'
    env_file:
      - .env
    build:
      context: ./server-api
      dockerfile: Dockerfile
    ports:
      - $PORT_API:$PORT_API
    restart: 'unless-stopped'
    volumes:
      - ./server-api/src/firebaseConfig.json:/app/src/firebaseConfig.json
