[package]
name = "houseflow-auth-types"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-token = { path = "../../token", features = [ "serde" ] }
serde = { version = "1.0", optional = true }
