[package]
name = "houseflow-types"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
rand = "0.8"
thiserror = "1.0"
bytes = "1"
semver = { version = "0.11", features = ["serde"] }

strum = "0.20"
strum_macros = "0.20"

serde = { version = "1.0", features = ["derive"], optional = true }

sqlx = { version = "0.5", features = [ "macros", "runtime-tokio-native-tls", "postgres" ], default-features = false, optional = true }
