[package]
name = "houseflow-types"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex            = "0.4"
rand           = "0.8"
thiserror      = "1.0"
bytes          = "1"
semver         = { version = "1.0.3", features = ["serde"] }

postgres-types = { version = "0.2.1", optional = true }

strum          = { version = "0.21.0", features = ["derive"] }

serde          = { version = "1.0", features = ["derive"], optional = true }

[features]
default        = [ "serde" ]
