[package]
name = "houseflow"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-types = { path = "../types/" }
houseflow-auth-api = { path = "../auth/api/", features = [ "keystore" ] }
houseflow-auth-types = { path = "../auth/types/" }
houseflow-auth-server = { path = "../auth/server/" }
houseflow-db = { path = "../db/" }

actix-rt = "2.2.0"

structopt = "0.3.21"
tokio = { version = "1.6.1", features = ["sync", "rt-multi-thread", "macros"] }
url = "2.2.2"
dialoguer = "0.8.0"
anyhow = "1.0.40"
log = "0.4.14"
loggerv = "0.7.2"
