[package]
name = "houseflow-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-lighthouse-proto 	= { path = "../lighthouse/proto" }
houseflow-lighthouse-types 	= { path = "../lighthouse/types", features = ["actix"] }
houseflow-fulfillment-types 	= { path = "../fulfillment/types", features = [ "actix", "db" ] }
houseflow-auth-types 		= { path = "../auth/types", features = [ "actix", "db" ] }
houseflow-db 			= { path = "../db" }
houseflow-types			= { path = "../types" }
houseflow-token 		= { path = "../token", features = ["actix", "store"] }
houseflow-config 		= { path = "../config", features = [ "server" ] }

actix 	 	 = "0.11.1"
actix-rt 	 = "2.2.0"
actix-web 	 = "4.0.0-beta.7" 
actix-web-actors = "4.0.0-beta.5"
actix-service 	 = "2.0.0-beta.5"
tokio            = { version = "1.5", features = ["sync" ] }

validator    = "0.13.0"
thiserror        = "1.0"
log              = "0.4"

itertools        = "0.10"

bytes            = "1.0"
serde            = "1.0"
serde_json       = "1.0"
rust-argon2 = "0.8.3"
semver = "1.0.3"
rand = "0.8.4"

