[package]
name = "houseflow-server"
version = "0.1.1"
description = "Server for Houseflow"
homepage = "https://github.com/gbaranski/houseflow"
repository = "https://github.com/gbaranski/houseflow"
authors = ["Grzegorz Baranski <root@gbaranski.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-db = { path="../db", version="0.1.0" }
houseflow-types = { path="../types", version="0.1.0", features=[
    "actix",
    "token",
    "auth",
    "fulfillment",
    "lighthouse",
] }
houseflow-config = { path="../config", version="0.1.0", features=["server"] }

actix = "0.12.0"
actix-rt = "2.2.0"
actix-web = "4.0.0-beta.8"
actix-web-actors = "4.0.0-beta.6"
actix-service = "2.0.0"
tokio = { version="1.5", features=["sync"] }

validator = "0.13.0"
thiserror = "1.0"
log = "0.4"

itertools = "0.10"

bytes = "1.0"
serde = "1.0"
serde_json = "1.0"
rust-argon2 = "0.8.3"
semver = "1.0.3"
rand = "0.8.4"
async-trait = "0.1.50"
redis = { version="0.20.1", features=["tokio-comp"] }

[dev-dependencies]
futures = "0.3.15"
