[package]
name = "houseflow-config"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.4"
serde = { version = "1.0.126", features = ["derive"] }
thiserror = "1.0.25"
tokio = { version = "1.7.1", optional = true, features = ["io-util", "fs"] }
types = { path = "../types/", package = "houseflow-types" }
xdg = "2.2.0"
toml = { version = "0.5.8", optional = true }

[features]
device = []
client = []
server = ["postgres", "redis"]
postgres = []
redis = []
fs = ["tokio", "toml"]

[dev-dependencies]
toml = "0.5.8"

