[package]
name = "houseflow-db"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-types = { path = "../types", features = [ "postgres-types" ] }

refinery = { version = "0.5.0", features = [ "tokio-postgres" ] }

tokio = "1.6"

tokio-postgres = "0.7"
deadpool-postgres = "0.8"

semver = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

log = "0.4"
env_logger = "0.8"
thiserror = "1.0"

[dev-dependencies]
rust-argon2 = "0.8"
tokio = { version = "1.6", features = ["macros", "rt-multi-thread"] }

