# Houseflow device configuration

# ID and Password(in plain-text) of your device, must match with the entry in database
device_id = "{}"
device_password = "{}"

# Address 
# server_hostname = "{}"
# use_tls = false

