[package]
name = "broker"
version = "0.1.0"
authors = ["gbaranski <root@gbaranski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
houseflow-types = { path = "../../types" }
lighthouse-proto = { path = "../proto" }
lighthouse-api = { path = "../api", default-features = false }

actix = "0.11.1"
actix-web = "4.0.0-beta.6"
actix-web-actors = { git = "https://github.com/actix/actix-web" }
tokio = { version = "1.5", features = [ "rt-multi-thread", "macros", "sync" ] }

thiserror = "1.0"
env_logger = "0.8"
log = "0.4"
