# Houseflow server configuration

# Change to "0.0.0.0:{}" to allow clients from outside network to connect
# address = "{}"

# Randomly generated secrets, keep them safe, don't share with anyone
[secrets]
refresh_key = "{}"
access_key = "{}"
authorization_code_key = "{}"
